// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

// Saat di-hosting, aplikasi akan mengambil kunci dari pengaturan Vercel.
// Saat di komputermu, Vite akan menggunakan file .env (jika ada).
const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  throw new Error("Supabase URL and Key are required. Make sure to set them in your environment variables.");
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);